name: Danger Check
on: [pull_request]

jobs:
  quality-check:
    name: Run
    runs-on: macos-15
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Danger
        run: brew install danger/tap/danger-swift

      - name: Run Danger
        run: danger-swift ci --failOnErrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
